### ISSUE TITLE
play does not end when chart is shorter then the song

### ISSUE THREAD

**Issue by ssapgosu12** [semyon422/soundsphere-updater#1]
game play does not end when chart is shorter then the song
i had to wait.

**Comment by Emanuel-de-Jong** [comment]
It doesn't end in general. It's a design choice.
If you disagree with it, you can leave your feedback in the discord server: https://discord.gg/ubKMtTk

**Comment by semyon422** [comment]
This issue is related to soundsphere, not soundsphere-updater. It will be fixed in future. Join our discord server for more active discussion.
